"""empty message

Revision ID: 02e4746bd834
Revises: d19e3a939845
Create Date: 2022-04-16 23:22:30.592671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02e4746bd834'
down_revision = 'd19e3a939845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_reports', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_reports', sa.Column('location', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
