"""empty message

Revision ID: 07de74b1d16d
Revises: 62580c4974d6
Create Date: 2022-04-17 16:11:09.590926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07de74b1d16d'
down_revision = '62580c4974d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortname', sa.String(length=32), nullable=True),
    sa.Column('comunity', sa.String(length=3), nullable=True),
    sa.Column('longname', sa.String(length=64), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_crops_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('crop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['tbl_crops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['tbl_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('reportid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reportid'], ['tbl_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_users_email'), 'tbl_users', ['email'], unique=True)
    op.create_index(op.f('ix_tbl_users_username'), 'tbl_users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_users_username'), table_name='tbl_users')
    op.drop_index(op.f('ix_tbl_users_email'), table_name='tbl_users')
    op.drop_table('tbl_users')
    op.drop_table('tbl_crops_report')
    op.drop_table('tbl_parameters')
    # ### end Alembic commands ###
