"""empty message

Revision ID: 080d83a2e0ed
Revises: 086d48b697aa
Create Date: 2022-04-20 14:10:49.769581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '080d83a2e0ed'
down_revision = '086d48b697aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('densityOfPopulation', sa.Integer(), nullable=True),
    sa.Column('cropType', sa.String(length=128), nullable=False),
    sa.Column('temperatureRange', sa.ARRAY(sa.Integer(), dimensions=3), nullable=True),
    sa.Column('humidityRange', sa.ARRAY(sa.Integer(), dimensions=3), nullable=True),
    sa.Column('soilmoistureRange', sa.ARRAY(sa.Integer(), dimensions=3), nullable=True),
    sa.Column('soiltemperatureRange', sa.ARRAY(sa.Integer(), dimensions=3), nullable=True),
    sa.Column('precipitationRange', sa.ARRAY(sa.Integer(), dimensions=3), nullable=True),
    sa.Column('radiationRange', sa.ARRAY(sa.Integer(), dimensions=3), nullable=True),
    sa.Column('windvelocityRange', sa.ARRAY(sa.Integer(), dimensions=3), nullable=True),
    sa.Column('pricePerKg', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortname', sa.String(length=32), nullable=True),
    sa.Column('comunity', sa.String(length=3), nullable=True),
    sa.Column('longname', sa.String(length=64), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('bbox', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('sides', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('polygon', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('params', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('numberOfPlants', sa.Integer(), nullable=True),
    sa.Column('avgMonthlyTemperaturePlants', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('avgMonthlyPrecipitationPlants', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('avgMonthlyHumidityPlants', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('avgMonthlySoilmoisturePlants', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('avgMonthlySoiltemperaturePlants', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('avgMonthlyRadiationPlants', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('avgMonthlyWindDirectionPlants', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('plantsScore', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_crops_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('crop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['tbl_crops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['tbl_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_mundi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('layerName', sa.String(length=48), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('colorCount', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('pixelColor', sa.ARRAY(sa.String(length=8)), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['tbl_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('reportid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reportid'], ['tbl_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_users_email'), 'tbl_users', ['email'], unique=True)
    op.create_index(op.f('ix_tbl_users_username'), 'tbl_users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_users_username'), table_name='tbl_users')
    op.drop_index(op.f('ix_tbl_users_email'), table_name='tbl_users')
    op.drop_table('tbl_users')
    op.drop_table('tbl_mundi')
    op.drop_table('tbl_crops_report')
    op.drop_table('tbl_reports')
    op.drop_table('tbl_parameters')
    op.drop_table('tbl_crops')
    # ### end Alembic commands ###
