"""empty message

Revision ID: 086d48b697aa
Revises: 2be1fe6b05d4
Create Date: 2022-04-20 11:17:14.578735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '086d48b697aa'
down_revision = '2be1fe6b05d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('bbox', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('sides', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('polygon', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('params', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('numberOfPlants', sa.Integer(), nullable=True),
    sa.Column('avgMonthlyTemperaturePlants', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('avgMonthlyPrecipitationPlants', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('avgMonthlyHumidityPlants', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('avgMonthlySoilmoisturePlants', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('avgMonthlySoiltemperaturePlants', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('avgMonthlyRadiationPlants', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('avgMonthlyWindDirectionPlants', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('plantsScore', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'tbl_crops_report', 'tbl_reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tbl_users', 'tbl_reports', ['reportid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_users', type_='foreignkey')
    op.drop_constraint(None, 'tbl_crops_report', type_='foreignkey')
    op.drop_table('tbl_reports')
    # ### end Alembic commands ###
