"""empty message

Revision ID: 128ddcb7c6c8
Revises: cad84236387b
Create Date: 2022-04-07 15:11:08.954160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128ddcb7c6c8'
down_revision = 'cad84236387b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.ARRAY(sa.Integer(), dimensions=5), nullable=False),
    sa.Column('avgMonthlytemperature', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlyprecipitation', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlyhumidity', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlysoilmoisture', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlyradiation', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgAnnualtemperature', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgAnnualprecipitation', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgAnnualhumidity', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgAnnualsoilmoisture', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgAnnualradiation', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_reports')
    # ### end Alembic commands ###
