"""empty message

Revision ID: 40d065b5dd14
Revises: 
Create Date: 2022-03-31 21:53:13.073635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d065b5dd14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_users', sa.Column('username', sa.String(length=64), nullable=True))
    op.add_column('tbl_users', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('tbl_users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_constraint('tbl_users_name_key', 'tbl_users', type_='unique')
    op.drop_constraint('tbl_users_password_key', 'tbl_users', type_='unique')
    op.create_index(op.f('ix_tbl_users_email'), 'tbl_users', ['email'], unique=True)
    op.create_index(op.f('ix_tbl_users_username'), 'tbl_users', ['username'], unique=True)
    op.drop_column('tbl_users', 'name')
    op.drop_column('tbl_users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tbl_users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tbl_users_username'), table_name='tbl_users')
    op.drop_index(op.f('ix_tbl_users_email'), table_name='tbl_users')
    op.create_unique_constraint('tbl_users_password_key', 'tbl_users', ['password'])
    op.create_unique_constraint('tbl_users_name_key', 'tbl_users', ['name'])
    op.drop_column('tbl_users', 'password_hash')
    op.drop_column('tbl_users', 'email')
    op.drop_column('tbl_users', 'username')
    # ### end Alembic commands ###
