"""empty message

Revision ID: 4d41e12c331b
Revises: eb9fce295ee4
Create Date: 2022-04-17 13:44:33.798747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d41e12c331b'
down_revision = 'eb9fce295ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.ARRAY(sa.Float(), dimensions=2), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('bbox', sa.ARRAY(sa.Float(), dimensions=4), nullable=True),
    sa.Column('polygon', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('areasquarehectare', sa.Float(), nullable=True),
    sa.Column('avgMonthlyTemperature', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlyPrecipitation', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlyHumidity', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlySoilmoisture', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlySoiltemperature', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlyRadiation', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlyWindDirection', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('windDirection', sa.String(length=128), nullable=True),
    sa.Column('numberOfPlants', sa.Integer(), nullable=True),
    sa.Column('avgMonthlyTemperaturePlants', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlyPrecipitationPlants', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlyHumidityPlants', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlySoilmoisturePlants', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlySoiltemperaturePlants', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlyRadiationPlants', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlyWindDirectionPlants', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('plantsScore', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_crops_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('crop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['tbl_crops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['tbl_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('reportid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reportid'], ['tbl_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_users_email'), 'tbl_users', ['email'], unique=True)
    op.create_index(op.f('ix_tbl_users_username'), 'tbl_users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_users_username'), table_name='tbl_users')
    op.drop_index(op.f('ix_tbl_users_email'), table_name='tbl_users')
    op.drop_table('tbl_users')
    op.drop_table('tbl_crops_report')
    op.drop_table('tbl_reports')
    # ### end Alembic commands ###
