"""empty message

Revision ID: 4f667e1e5074
Revises: ec616189b325
Create Date: 2022-04-16 16:46:32.849285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f667e1e5074'
down_revision = 'ec616189b325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_reports', sa.Column('bbox', sa.ARRAY(sa.Integer(), dimensions=4), nullable=True))
    op.add_column('tbl_reports', sa.Column('polygon', sa.LargeBinary(), nullable=True))
    op.alter_column('tbl_reports', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_column('tbl_reports', 'polygonLocation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_reports', sa.Column('polygonLocation', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.alter_column('tbl_reports', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('tbl_reports', 'polygon')
    op.drop_column('tbl_reports', 'bbox')
    # ### end Alembic commands ###
