"""empty message

Revision ID: 57cfff3cd701
Revises: 70b554baa9df
Create Date: 2022-04-24 18:50:19.771102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57cfff3cd701'
down_revision = '70b554baa9df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('timetogrowmonths', sa.Integer(), nullable=False),
    sa.Column('densityOfPopulation', sa.Integer(), nullable=True),
    sa.Column('cropType', sa.String(length=128), nullable=False),
    sa.Column('waterPerArea', sa.Float(), nullable=True),
    sa.Column('waterperiod', sa.Integer(), nullable=True),
    sa.Column('temperatureRange', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('humidityRange', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('soilmoistureRange', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('soiltemperatureRange', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('precipitationRange', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('radiationRange', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('windvelocityRange', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('pricePerKg', sa.Float(), nullable=True),
    sa.Column('kgspersqm', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_crops')
    # ### end Alembic commands ###
