"""empty message

Revision ID: 5857d6966fca
Revises: c516ebbdec5f
Create Date: 2022-04-23 17:39:31.914619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5857d6966fca'
down_revision = 'c516ebbdec5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('timetogrowmonths', sa.Integer(), nullable=False),
    sa.Column('densityOfPopulation', sa.Integer(), nullable=True),
    sa.Column('cropType', sa.String(length=128), nullable=False),
    sa.Column('waterPerArea', sa.Float(), nullable=True),
    sa.Column('waterperiod', sa.Integer(), nullable=True),
    sa.Column('temperatureRange', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('humidityRange', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('soilmoistureRange', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('soiltemperatureRange', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('precipitationRange', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('radiationRange', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('windvelocityRange', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('pricePerKg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_crops')
    # ### end Alembic commands ###
