"""empty message

Revision ID: 60135e01f337
Revises: 128ddcb7c6c8
Create Date: 2022-04-07 15:16:36.765003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60135e01f337'
down_revision = '128ddcb7c6c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_users', sa.Column('reportid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tbl_users', 'tbl_reports', ['reportid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_users', type_='foreignkey')
    op.drop_column('tbl_users', 'reportid')
    # ### end Alembic commands ###
