"""empty message

Revision ID: 88e1cdfe7100
Revises: f17e9ca54ecd
Create Date: 2022-04-17 22:52:57.157535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88e1cdfe7100'
down_revision = 'f17e9ca54ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_crops', sa.Column('waterPerArea', sa.Integer(), nullable=True))
    op.add_column('tbl_reports', sa.Column('bbox', sa.ARRAY(sa.Float()), nullable=True))
    op.add_column('tbl_reports', sa.Column('polygon', sa.ARRAY(sa.Float()), nullable=True))
    op.add_column('tbl_reports', sa.Column('area', sa.Float(), nullable=True))
    op.alter_column('tbl_reports', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_column('tbl_reports', 'polygonLocation')
    op.drop_column('tbl_reports', 'areaSquareHectare')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_reports', sa.Column('areaSquareHectare', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tbl_reports', sa.Column('polygonLocation', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.alter_column('tbl_reports', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('tbl_reports', 'area')
    op.drop_column('tbl_reports', 'polygon')
    op.drop_column('tbl_reports', 'bbox')
    op.drop_column('tbl_crops', 'waterPerArea')
    # ### end Alembic commands ###
