"""empty message

Revision ID: a8c7f623a81c
Revises: 1edfcc453878
Create Date: 2022-04-14 10:20:27.377614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c7f623a81c'
down_revision = '1edfcc453878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('densityOfPopulation', sa.Integer(), nullable=True),
    sa.Column('cropType', sa.String(length=128), nullable=False),
    sa.Column('temperatureRange', sa.ARRAY(sa.Integer(), dimensions=3), nullable=True),
    sa.Column('humidityRange', sa.ARRAY(sa.Integer(), dimensions=3), nullable=True),
    sa.Column('soilmoistureRange', sa.ARRAY(sa.Integer(), dimensions=3), nullable=True),
    sa.Column('soiltemperatureRange', sa.ARRAY(sa.Integer(), dimensions=3), nullable=True),
    sa.Column('precipitationRange', sa.ARRAY(sa.Integer(), dimensions=3), nullable=True),
    sa.Column('radiationRange', sa.ARRAY(sa.Integer(), dimensions=3), nullable=True),
    sa.Column('windvelocityRange', sa.ARRAY(sa.Integer(), dimensions=3), nullable=True),
    sa.Column('pricePerKg', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortname', sa.String(length=32), nullable=True),
    sa.Column('comunity', sa.String(length=3), nullable=True),
    sa.Column('longname', sa.String(length=64), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.ARRAY(sa.Integer(), dimensions=2), nullable=False),
    sa.Column('polygonLocation', sa.LargeBinary(), nullable=True),
    sa.Column('areaSquareHectare', sa.Integer(), nullable=True),
    sa.Column('windDirection', sa.String(length=128), nullable=True),
    sa.Column('avgMonthlyTemperature', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlyPrecipitation', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlyHumidity', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlySoilmoisture', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlySoiltemperature', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlyRadiation', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlyWindDirection', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('numberOfPlants', sa.Integer(), nullable=True),
    sa.Column('avgMonthlyTemperaturePlants', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlyPrecipitationPlants', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlyHumidityPlants', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlySoilmoisturePlants', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlySoiltemperaturePlants', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlyRadiationPlants', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('avgMonthlyWindDirectionPlants', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.Column('plantsScore', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_crops_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('crop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['tbl_crops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['tbl_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tbl_users', sa.Column('reportid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tbl_users', 'tbl_reports', ['reportid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_users', type_='foreignkey')
    op.drop_column('tbl_users', 'reportid')
    op.drop_table('tbl_crops_report')
    op.drop_table('tbl_reports')
    op.drop_table('tbl_parameters')
    op.drop_table('tbl_crops')
    # ### end Alembic commands ###
