"""empty message

Revision ID: b21b8d8c4060
Revises: 4e17fb81e349
Create Date: 2022-04-24 17:36:55.838767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b21b8d8c4060'
down_revision = '4e17fb81e349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_crops_report')
    op.add_column('tbl_crops', sa.Column('timetogrowmonths', sa.Integer(), nullable=False))
    op.add_column('tbl_crops', sa.Column('waterperiod', sa.Integer(), nullable=True))
    op.add_column('tbl_crops', sa.Column('kgspersqm', sa.Float(), nullable=True))
    op.add_column('tbl_reports', sa.Column('sides', sa.ARRAY(sa.Float()), nullable=True))
    op.add_column('tbl_reports', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('tbl_reports', sa.Column('params', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('tbl_reports', sa.Column('avgMonthlyWindVelocityPlants', sa.ARRAY(sa.Float()), nullable=True))
    op.add_column('tbl_reports', sa.Column('plantsScores', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('tbl_reports', sa.Column('plantsNames', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('tbl_reports', sa.Column('plantsBadges', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('tbl_reports', sa.Column('plantsLifePeriod', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('tbl_reports', sa.Column('priceperkg', sa.ARRAY(sa.Float()), nullable=True))
    op.add_column('tbl_reports', sa.Column('waterneeded', sa.ARRAY(sa.Float()), nullable=True))
    op.add_column('tbl_reports', sa.Column('watercost', sa.ARRAY(sa.Float()), nullable=True))
    op.add_column('tbl_reports', sa.Column('benefit', sa.ARRAY(sa.Float()), nullable=True))
    op.create_foreign_key(None, 'tbl_reports', 'tbl_users', ['user_id'], ['id'])
    op.drop_column('tbl_reports', 'avgMonthlySoiltemperature')
    op.drop_column('tbl_reports', 'windDirection')
    op.drop_column('tbl_reports', 'avgMonthlyWindDirection')
    op.drop_column('tbl_reports', 'avgMonthlySoilmoisture')
    op.drop_column('tbl_reports', 'avgMonthlyWindDirectionPlants')
    op.drop_column('tbl_reports', 'avgMonthlyPrecipitation')
    op.drop_column('tbl_reports', 'plantsScore')
    op.drop_column('tbl_reports', 'avgMonthlyRadiation')
    op.drop_column('tbl_reports', 'avgMonthlyTemperature')
    op.drop_column('tbl_reports', 'avgMonthlyHumidity')
    op.drop_constraint('tbl_users_reportid_fkey', 'tbl_users', type_='foreignkey')
    op.drop_column('tbl_users', 'reportid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_users', sa.Column('reportid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tbl_users_reportid_fkey', 'tbl_users', 'tbl_reports', ['reportid'], ['id'])
    op.add_column('tbl_reports', sa.Column('avgMonthlyHumidity', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('tbl_reports', sa.Column('avgMonthlyTemperature', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('tbl_reports', sa.Column('avgMonthlyRadiation', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('tbl_reports', sa.Column('plantsScore', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('tbl_reports', sa.Column('avgMonthlyPrecipitation', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('tbl_reports', sa.Column('avgMonthlyWindDirectionPlants', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('tbl_reports', sa.Column('avgMonthlySoilmoisture', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('tbl_reports', sa.Column('avgMonthlyWindDirection', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('tbl_reports', sa.Column('windDirection', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('tbl_reports', sa.Column('avgMonthlySoiltemperature', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tbl_reports', type_='foreignkey')
    op.drop_column('tbl_reports', 'benefit')
    op.drop_column('tbl_reports', 'watercost')
    op.drop_column('tbl_reports', 'waterneeded')
    op.drop_column('tbl_reports', 'priceperkg')
    op.drop_column('tbl_reports', 'plantsLifePeriod')
    op.drop_column('tbl_reports', 'plantsBadges')
    op.drop_column('tbl_reports', 'plantsNames')
    op.drop_column('tbl_reports', 'plantsScores')
    op.drop_column('tbl_reports', 'avgMonthlyWindVelocityPlants')
    op.drop_column('tbl_reports', 'params')
    op.drop_column('tbl_reports', 'user_id')
    op.drop_column('tbl_reports', 'sides')
    op.drop_column('tbl_crops', 'kgspersqm')
    op.drop_column('tbl_crops', 'waterperiod')
    op.drop_column('tbl_crops', 'timetogrowmonths')
    op.create_table('tbl_crops_report',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('crop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['tbl_crops.id'], name='tbl_crops_report_crop_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['tbl_reports.id'], name='tbl_crops_report_report_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='tbl_crops_report_pkey')
    )
    # ### end Alembic commands ###
