"""empty message

Revision ID: b286a854701f
Revises: 1f8dc7601c21
Create Date: 2022-04-21 18:16:04.269534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b286a854701f'
down_revision = '1f8dc7601c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_crops', sa.Column('timetogrowmonths', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_crops', 'timetogrowmonths')
    # ### end Alembic commands ###
