"""empty message

Revision ID: beb580d48477
Revises: 02e4746bd834
Create Date: 2022-04-16 23:28:34.418159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb580d48477'
down_revision = '02e4746bd834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_reports', sa.Column('location', sa.ARRAY(sa.Integer(), dimensions=2), nullable=True))
    op.add_column('tbl_reports', sa.Column('name', sa.String(length=128), nullable=True))
    op.add_column('tbl_reports', sa.Column('bbox', sa.ARRAY(sa.Integer(), dimensions=4), nullable=True))
    op.add_column('tbl_reports', sa.Column('polygon', sa.LargeBinary(), nullable=True))
    op.add_column('tbl_reports', sa.Column('areaSquareHectare', sa.Integer(), nullable=True))
    op.add_column('tbl_reports', sa.Column('avgMonthlyTemperature', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True))
    op.add_column('tbl_reports', sa.Column('avgMonthlyPrecipitation', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True))
    op.add_column('tbl_reports', sa.Column('avgMonthlyHumidity', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True))
    op.add_column('tbl_reports', sa.Column('avgMonthlySoilmoisture', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True))
    op.add_column('tbl_reports', sa.Column('avgMonthlySoiltemperature', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True))
    op.add_column('tbl_reports', sa.Column('avgMonthlyRadiation', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True))
    op.add_column('tbl_reports', sa.Column('avgMonthlyWindDirection', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True))
    op.add_column('tbl_reports', sa.Column('windDirection', sa.String(length=128), nullable=True))
    op.add_column('tbl_reports', sa.Column('numberOfPlants', sa.Integer(), nullable=True))
    op.add_column('tbl_reports', sa.Column('avgMonthlyTemperaturePlants', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True))
    op.add_column('tbl_reports', sa.Column('avgMonthlyPrecipitationPlants', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True))
    op.add_column('tbl_reports', sa.Column('avgMonthlyHumidityPlants', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True))
    op.add_column('tbl_reports', sa.Column('avgMonthlySoilmoisturePlants', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True))
    op.add_column('tbl_reports', sa.Column('avgMonthlySoiltemperaturePlants', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True))
    op.add_column('tbl_reports', sa.Column('avgMonthlyRadiationPlants', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True))
    op.add_column('tbl_reports', sa.Column('avgMonthlyWindDirectionPlants', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True))
    op.add_column('tbl_reports', sa.Column('plantsScore', sa.ARRAY(sa.Integer(), dimensions=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_reports', 'plantsScore')
    op.drop_column('tbl_reports', 'avgMonthlyWindDirectionPlants')
    op.drop_column('tbl_reports', 'avgMonthlyRadiationPlants')
    op.drop_column('tbl_reports', 'avgMonthlySoiltemperaturePlants')
    op.drop_column('tbl_reports', 'avgMonthlySoilmoisturePlants')
    op.drop_column('tbl_reports', 'avgMonthlyHumidityPlants')
    op.drop_column('tbl_reports', 'avgMonthlyPrecipitationPlants')
    op.drop_column('tbl_reports', 'avgMonthlyTemperaturePlants')
    op.drop_column('tbl_reports', 'numberOfPlants')
    op.drop_column('tbl_reports', 'windDirection')
    op.drop_column('tbl_reports', 'avgMonthlyWindDirection')
    op.drop_column('tbl_reports', 'avgMonthlyRadiation')
    op.drop_column('tbl_reports', 'avgMonthlySoiltemperature')
    op.drop_column('tbl_reports', 'avgMonthlySoilmoisture')
    op.drop_column('tbl_reports', 'avgMonthlyHumidity')
    op.drop_column('tbl_reports', 'avgMonthlyPrecipitation')
    op.drop_column('tbl_reports', 'avgMonthlyTemperature')
    op.drop_column('tbl_reports', 'areaSquareHectare')
    op.drop_column('tbl_reports', 'polygon')
    op.drop_column('tbl_reports', 'bbox')
    op.drop_column('tbl_reports', 'name')
    op.drop_column('tbl_reports', 'location')
    # ### end Alembic commands ###
