"""empty message

Revision ID: bf35beed8725
Revises: 17c6b17c58b5
Create Date: 2022-04-16 23:31:35.800965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf35beed8725'
down_revision = '17c6b17c58b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_reports', 'location',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_reports', 'location',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=True)
    # ### end Alembic commands ###
