"""empty message

Revision ID: c516ebbdec5f
Revises: b286a854701f
Create Date: 2022-04-22 20:25:40.275570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c516ebbdec5f'
down_revision = 'b286a854701f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('timetogrowmonths', sa.Integer(), nullable=False),
    sa.Column('densityOfPopulation', sa.Integer(), nullable=True),
    sa.Column('cropType', sa.String(length=128), nullable=False),
    sa.Column('waterPerArea', sa.Integer(), nullable=True),
    sa.Column('temperatureRange', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('humidityRange', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('soilmoistureRange', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('soiltemperatureRange', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('precipitationRange', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('radiationRange', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('windvelocityRange', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('pricePerKg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('bbox', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('sides', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('polygon', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('params', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('numberOfPlants', sa.Integer(), nullable=True),
    sa.Column('avgMonthlyTemperaturePlants', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('avgMonthlyPrecipitationPlants', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('avgMonthlyHumidityPlants', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('avgMonthlySoilmoisturePlants', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('avgMonthlySoiltemperaturePlants', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('avgMonthlyRadiationPlants', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('avgMonthlyWindDirectionPlants', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('plantsScores', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('plantsNames', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('plantsBadges', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_reports')
    op.drop_table('tbl_crops')
    # ### end Alembic commands ###
