"""empty message

Revision ID: ec616189b325
Revises: a8c7f623a81c
Create Date: 2022-04-15 19:02:10.818542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec616189b325'
down_revision = 'a8c7f623a81c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_reports', sa.Column('bbox', sa.ARRAY(sa.Integer(), dimensions=4), nullable=True))
    op.add_column('tbl_reports', sa.Column('polygon', sa.LargeBinary(), nullable=True))
    op.alter_column('tbl_reports', 'location',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=True)
    op.drop_column('tbl_reports', 'polygonLocation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_reports', sa.Column('polygonLocation', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.alter_column('tbl_reports', 'location',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=False)
    op.drop_column('tbl_reports', 'polygon')
    op.drop_column('tbl_reports', 'bbox')
    # ### end Alembic commands ###
