"""empty message

Revision ID: f8261894c738
Revises: 60135e01f337
Create Date: 2022-04-07 15:28:51.414917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8261894c738'
down_revision = '60135e01f337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cropType', sa.String(length=128), nullable=False),
    sa.Column('temperatureRange', sa.ARRAY(sa.Integer(), dimensions=2), nullable=True),
    sa.Column('humidityRange', sa.ARRAY(sa.Integer(), dimensions=2), nullable=True),
    sa.Column('soilmoistureRange', sa.ARRAY(sa.Integer(), dimensions=2), nullable=True),
    sa.Column('precipitationRange', sa.ARRAY(sa.Integer(), dimensions=2), nullable=True),
    sa.Column('radiationRange', sa.ARRAY(sa.Integer(), dimensions=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_crops')
    # ### end Alembic commands ###
